#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../lib/pnpm-global/5/node_modules/degit/degit" "$@"
else
  exec node  "$basedir/../lib/pnpm-global/5/node_modules/degit/degit" "$@"
fi
